### ISSUE TITLE
Question about the metric type for logstash_node_queue_events

### ISSUE THREAD

**Issue by leejones** [sequra/logstash_exporter#12]
I noticed that the metric type for `logstash_node_queue_events` is a counter, for example:

```
$ curl -s localhost:9198/metrics | grep queue_events
# HELP logstash_node_queue_events queue_events
# TYPE logstash_node_queue_events counter
logstash_node_queue_events{pipeline=".monitoring-logstash"} 0
logstash_node_queue_events{pipeline="main"} 0
```

However, the number of queued events will increase and decrease over time as items are pushed onto the queue and pulled off of it. Based on that, I think this should be a [gauge](https://prometheus.io/docs/concepts/metric_types/#gauge) metric type instead. Can you help me understand what might be happening here?

**Comment by mpucholblasco** [comment]
Good question @leejones . Not sure about it. This information is extracted from Logstash Monitoring API, and concretely from [Pipeline Stats](https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#pipeline-stats). There is no documentation about the type of this metrics, so I'm not sure about which should be exactly. In this cases, I assume that this type is the same as in other places (wrongly in this case).

If you are sure that this type should be a gauge, we can change it on code.

**Comment by leejones** [comment]
Thanks for the info @mpucholblasco! I'm pretty confident that this metric would meet the criteria for a gauge, however I just noticed that metric type [isn't really used](https://prometheus.io/docs/concepts/metric_types/) by Prometheus on the server side:

>  The Prometheus server does not yet make use of the type information and flattens all data into untyped time series. This may change in the future.

So it sounds like it's not a big deal. If I run into any issues with the current metric types, I'll open issue with more details. For now though, we probably don't need to worry about it. Thanks!
