### ISSUE TITLE
Support for Filebeat input

### ISSUE THREAD

**Issue by andronkyr** [sequra/logstash_exporter#16]
Hello,

We have been using the exporter and it has provided us with some great insights regarding our pipeline.

I was wondering whether the filebeat input could also be supported? 

As far as I know, it exposes some extra fields (`current_connections`, `peak_connections`)  that would be interesting to monitor:
```
{
        "id" : "XX",
        "events" : {
          "out" : 1000,
          "queue_push_duration_in_millis" : 1000
        },
        "current_connections" : 0,
        "name" : "beats",
        "peak_connections" : 0
      }
```

Thank you in advance :)

**Comment by mpucholblasco** [comment]
Hello @andronkyr , there is another specialised exporter for it on https://github.com/trustpilot/beat-exporter. Not sure if it could fit your needs.

Please, could you review it and tell us your conclusions?

Thanks!

**Comment by andronkyr** [comment]
Hello @mpucholblasco :) 

Thanks for the recommendation. I would like to measure the number of connections on the logstash end and not at the distributed beat instances.

I think that this could be achieved by including the two aforementioned fields in the exporter. These are exposed by logstash when you are using beats as an input plugin. Unfortunately I haven't found any documentation on that but the snip above comes from a running logstash instance.

Thank you

**Comment by mpucholblasco** [comment]
Ok, @andronkyr , I understood that you needed this info from filebeat. Ok, understood. Adding as feature.
Thanks for clarifying.

**Comment by mpucholblasco** [comment]
@andronkyr , added feature on PR #19 . I tested it on an integration test with 7.5.2 version, but could you test it too to ensure it works as expected?

Thanks.

**Comment by andronkyr** [comment]
Hello @mpucholblasco 

Thank you very much. I can verify that it works :)
