### ISSUE TITLE
any example grafana dashboards?

### ISSUE THREAD

**Issue by dominik-ba** [sequra/logstash_exporter#26]
We use this exporter and are struggling with coming up with a nice dashboard.
Therefore I was wondering if there is already one which you can share?

I did not find one in the grafana dashboard lib.

**Comment by mpucholblasco** [comment]
In fact, we are not currently using `logstash-exporter`, just maintaining it (in fact, we want to traspass the maintenance...).

Anybody else could help providing a Grafana dashboard?

**Comment by B-Souty** [comment]
There is a really nice dashboard on grafana.com

https://grafana.com/grafana/dashboards/2525

I actually found this project thanks to this dashboard.

**Comment by dominik-ba** [comment]
Thanks :)
